test compile precise-output
target x86_64 has_avx512f has_avx512bw has_avx512dq has_avx512vl

;; CLIF-correct 512-bit fmin/fmax (NaN => quiet NaN, fmin(+0,-0) = -0,
;; fmax(-0,+0) = +0) and fcvt_to_sint_sat (NaN => 0, positive overflow =>
;; INT_MAX, negative overflow => INT_MIN).

function %fmin_f32x16(f32x16, f32x16) -> f32x16 {
block0(v0: f32x16, v1: f32x16):
    v2 = fmin v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vminps %zmm1, %zmm0, %zmm3
;   vminps %zmm0, %zmm1, %zmm5
;   vpord %zmm5, %zmm3, %zmm7
;   vcmpps $0x3, %zmm1, %zmm0, %k2
;   movl $0x7fc00000, %r11d
;   movd %r11d, %xmm0
;   vpbroadcastd %xmm0, %zmm0
;   vpblendmd %zmm0, %zmm7, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vminps %zmm1, %zmm0, %zmm3
;   vminps %zmm0, %zmm1, %zmm5
;   vpord %zmm5, %zmm3, %zmm7
;   vcmpunordps %zmm1, %zmm0, %k2
;   movl $0x7fc00000, %r11d
;   movd %r11d, %xmm0
;   vpbroadcastd %xmm0, %zmm0
;   vpblendmd %zmm0, %zmm7, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %fmax_f32x16(f32x16, f32x16) -> f32x16 {
block0(v0: f32x16, v1: f32x16):
    v2 = fmax v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vmaxps %zmm1, %zmm0, %zmm3
;   vmaxps %zmm0, %zmm1, %zmm5
;   vpandd %zmm5, %zmm3, %zmm7
;   vcmpps $0x3, %zmm1, %zmm0, %k2
;   movl $0x7fc00000, %r11d
;   movd %r11d, %xmm0
;   vpbroadcastd %xmm0, %zmm0
;   vpblendmd %zmm0, %zmm7, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vmaxps %zmm1, %zmm0, %zmm3
;   vmaxps %zmm0, %zmm1, %zmm5
;   vpandd %zmm5, %zmm3, %zmm7
;   vcmpunordps %zmm1, %zmm0, %k2
;   movl $0x7fc00000, %r11d
;   movd %r11d, %xmm0
;   vpbroadcastd %xmm0, %zmm0
;   vpblendmd %zmm0, %zmm7, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %fmin_f64x8(f64x8, f64x8) -> f64x8 {
block0(v0: f64x8, v1: f64x8):
    v2 = fmin v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vminpd %zmm1, %zmm0, %zmm3
;   vminpd %zmm0, %zmm1, %zmm5
;   vporq %zmm5, %zmm3, %zmm7
;   vcmppd $0x3, %zmm1, %zmm0, %k2
;   movabsq $0x7ff8000000000000, %r11
;   movq %r11, %xmm0
;   vpbroadcastq %xmm0, %zmm0
;   vpblendmq %zmm0, %zmm7, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vminpd %zmm1, %zmm0, %zmm3
;   vminpd %zmm0, %zmm1, %zmm5
;   vporq %zmm5, %zmm3, %zmm7
;   vcmpunordpd %zmm1, %zmm0, %k2
;   movabsq $0x7ff8000000000000, %r11
;   movq %r11, %xmm0
;   vpbroadcastq %xmm0, %zmm0
;   vpblendmq %zmm0, %zmm7, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %fmax_f64x8(f64x8, f64x8) -> f64x8 {
block0(v0: f64x8, v1: f64x8):
    v2 = fmax v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vmaxpd %zmm1, %zmm0, %zmm3
;   vmaxpd %zmm0, %zmm1, %zmm5
;   vpandq %zmm5, %zmm3, %zmm7
;   vcmppd $0x3, %zmm1, %zmm0, %k2
;   movabsq $0x7ff8000000000000, %r11
;   movq %r11, %xmm0
;   vpbroadcastq %xmm0, %zmm0
;   vpblendmq %zmm0, %zmm7, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vmaxpd %zmm1, %zmm0, %zmm3
;   vmaxpd %zmm0, %zmm1, %zmm5
;   vpandq %zmm5, %zmm3, %zmm7
;   vcmpunordpd %zmm1, %zmm0, %k2
;   movabsq $0x7ff8000000000000, %r11
;   movq %r11, %xmm0
;   vpbroadcastq %xmm0, %zmm0
;   vpblendmq %zmm0, %zmm7, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %fcvt_to_sint_sat_f32x16(f32x16) -> i32x16 {
block0(v0: f32x16):
    v1 = fcvt_to_sint_sat.i32x16 v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vcvttps2dq %zmm0, %zmm2
;   vcmpps $0x3, %zmm0, %zmm0, %k4
;   uninit  %xmm6
;   vpxord %zmm6, %zmm6, %zmm1
;   vpblendmd %zmm1, %zmm2, %zmm1 {%k4}
;   movl $0x4f000000, %eax
;   movd %eax, %xmm2
;   vpbroadcastd %xmm2, %zmm2
;   vcmpps $0x1d, %zmm2, %zmm0, %k2
;   movl $0x7fffffff, %eax
;   movd %eax, %xmm0
;   vpbroadcastd %xmm0, %zmm0
;   vpblendmd %zmm0, %zmm1, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vcvttps2dq %zmm0, %zmm2
;   vcmpunordps %zmm0, %zmm0, %k4
;   vpxord %zmm6, %zmm6, %zmm1
;   vpblendmd %zmm1, %zmm2, %zmm1 {%k4}
;   movl $0x4f000000, %eax
;   movd %eax, %xmm2
;   vpbroadcastd %xmm2, %zmm2
;   vcmpge_oqps %zmm2, %zmm0, %k2
;   movl $0x7fffffff, %eax
;   movd %eax, %xmm0
;   vpbroadcastd %xmm0, %zmm0
;   vpblendmd %zmm0, %zmm1, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %fcvt_to_sint_sat_f64x8(f64x8) -> i64x8 {
block0(v0: f64x8):
    v1 = fcvt_to_sint_sat.i64x8 v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vcvttpd2qq %zmm0, %zmm2
;   vcmppd $0x3, %zmm0, %zmm0, %k4
;   uninit  %xmm6
;   vpxord %zmm6, %zmm6, %zmm1
;   vpblendmq %zmm1, %zmm2, %zmm1 {%k4}
;   movabsq $0x43e0000000000000, %rax
;   movq %rax, %xmm2
;   vpbroadcastq %xmm2, %zmm2
;   vcmppd $0x1d, %zmm2, %zmm0, %k2
;   movabsq $0x7fffffffffffffff, %rax
;   movq %rax, %xmm0
;   vpbroadcastq %xmm0, %zmm0
;   vpblendmq %zmm0, %zmm1, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vcvttpd2qq %zmm0, %zmm2
;   vcmpunordpd %zmm0, %zmm0, %k4
;   vpxord %zmm6, %zmm6, %zmm1
;   vpblendmq %zmm1, %zmm2, %zmm1 {%k4}
;   movabsq $0x43e0000000000000, %rax
;   movq %rax, %xmm2
;   vpbroadcastq %xmm2, %zmm2
;   vcmpge_oqpd %zmm2, %zmm0, %k2
;   movabsq $0x7fffffffffffffff, %rax
;   movq %rax, %xmm0
;   vpbroadcastq %xmm0, %zmm0
;   vpblendmq %zmm0, %zmm1, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

