test compile precise-output
target x86_64 has_avx512f has_avx512bw has_avx512dq has_avx512vl

;; VPTERNLOG 3-input boolean fusion: each of the fused shapes below must
;; lower to a SINGLE vpternlogd/vpternlogq with the documented imm8.
;;
;; imm8 truth tables (A = first/tied operand = 0xF0, B = 0xCC, C = 0xAA):
;;   A^B^C       = 0x96
;;   A&B&C       = 0x80
;;   A|B|C       = 0xFE
;;   (A&B)|C     = 0xEA
;;   (A|B)&C     = 0xA8
;;
;; I64X8 uses vpternlogq; I32X16/I16X32/I8X64 use vpternlogd (bitwise ops
;; are lane-size agnostic).

;; ---------------------------------------------------------------------------
;; xor3, both associations
;; ---------------------------------------------------------------------------

function %xor3_left_i32x16(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = bxor v0, v1
    v4 = bxor v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %xor3_right_i32x16(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = bxor v1, v2
    v4 = bxor v0, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %xor3_left_i64x8(i64x8, i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8, v2: i64x8):
    v3 = bxor v0, v1
    v4 = bxor v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogq $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogq $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %xor3_right_i64x8(i64x8, i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8, v2: i64x8):
    v3 = bxor v1, v2
    v4 = bxor v0, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogq $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogq $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; ---------------------------------------------------------------------------
;; and3, both associations
;; ---------------------------------------------------------------------------

function %and3_left_i32x16(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = band v0, v1
    v4 = band v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0x80, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0x80, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %and3_right_i64x8(i64x8, i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8, v2: i64x8):
    v3 = band v1, v2
    v4 = band v0, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogq $0x80, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogq $0x80, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; ---------------------------------------------------------------------------
;; or3, both associations
;; ---------------------------------------------------------------------------

function %or3_left_i32x16(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = bor v0, v1
    v4 = bor v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0xfe, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0xfe, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %or3_right_i64x8(i64x8, i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8, v2: i64x8):
    v3 = bor v1, v2
    v4 = bor v0, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogq $0xfe, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogq $0xfe, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; ---------------------------------------------------------------------------
;; (a & b) | c, both operand orders of the root
;; ---------------------------------------------------------------------------

function %andor_i32x16(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = band v0, v1
    v4 = bor v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0xea, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0xea, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %andor_commuted_i32x16(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = band v0, v1
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0xea, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0xea, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %andor_i64x8(i64x8, i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8, v2: i64x8):
    v3 = band v0, v1
    v4 = bor v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogq $0xea, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogq $0xea, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; ---------------------------------------------------------------------------
;; (a | b) & c, both operand orders of the root
;; ---------------------------------------------------------------------------

function %orand_i32x16(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = bor v0, v1
    v4 = band v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0xa8, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0xa8, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %orand_commuted_i32x16(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = bor v0, v1
    v4 = band v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0xa8, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0xa8, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %orand_i64x8(i64x8, i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8, v2: i64x8):
    v3 = bor v0, v1
    v4 = band v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogq $0xa8, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogq $0xa8, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; ---------------------------------------------------------------------------
;; Narrow-lane types: bitwise fusion uses vpternlogd regardless of lane size
;; ---------------------------------------------------------------------------

function %xor3_i16x32(i16x32, i16x32, i16x32) -> i16x32 {
block0(v0: i16x32, v1: i16x32, v2: i16x32):
    v3 = bxor v0, v1
    v4 = bxor v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0x96, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %and3_i8x64(i8x64, i8x64, i8x64) -> i8x64 {
block0(v0: i8x64, v1: i8x64, v2: i8x64):
    v3 = band v0, v1
    v4 = band v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0x80, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0x80, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %orand_i16x32(i16x32, i16x32, i16x32) -> i16x32 {
block0(v0: i16x32, v1: i16x32, v2: i16x32):
    v3 = bor v0, v1
    v4 = band v3, v2
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0xa8, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0xa8, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; ---------------------------------------------------------------------------
;; Aliased inputs (tie/RMW hazard cases): the same SSA value feeds two of the
;; three VPTERNLOG inputs, including the tied first operand.
;; ---------------------------------------------------------------------------

;; a ^ a ^ c: A and B are the same register.
function %xor_aac_i32x16(i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16):
    v2 = bxor v0, v0
    v3 = bxor v2, v1
    return v3
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0x96, %zmm1, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0x96, %zmm1, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; (a & a) | c: A and B are the same register.
function %and_aa_or_c_i64x8(i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8):
    v2 = band v0, v0
    v3 = bor v2, v1
    return v3
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogq $0xea, %zmm1, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogq $0xea, %zmm1, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; (a | b) & a: A (tied) is also C.
function %orand_aba_i32x16(i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16):
    v2 = bor v0, v1
    v3 = band v2, v0
    return v3
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0xa8, %zmm0, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0xa8, %zmm0, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; ---------------------------------------------------------------------------
;; Value reused outside the fused tree: the tied operand (v0) is live after
;; the vpternlog, forcing regalloc to preserve it.
;; ---------------------------------------------------------------------------

function %xor3_tied_live_after_i32x16(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = bxor v0, v1
    v4 = bxor v3, v2
    v5 = iadd v4, v0
    return v5
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vmovdqu32 %zmm0, %zmm5
;   vpternlogd $0x96, %zmm2, %zmm1, %zmm5
;   vpaddd %zmm0, %zmm5, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vmovdqu32 %zmm0, %zmm5
;   vpternlogd $0x96, %zmm2, %zmm1, %zmm5
;   vpaddd %zmm0, %zmm5, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

