test compile precise-output
target x86_64 has_avx512f has_avx512bw has_avx512dq has_avx512vl

;; Bit-exact 512-bit bitselect / swizzle / float lane-access lowerings.
;;
;; - bitselect with a comparison condition locks the VPMOVD2M/Q + VPBLENDMD/Q
;;   whole-lane blend path (valid because comparison lanes are all-ones or
;;   all-zeros).
;; - bitselect with an arbitrary condition locks the bitwise VPTERNLOGD/Q
;;   (imm8=0xCA, A?B:C) path.
;; - swizzle locks the VPCMPUD/Q + VPERMD/Q + zero-blend sequence which
;;   implements CLIF's out-of-range-index-produces-zero semantics.
;; - extractlane/insertlane on F32X16/F64X8 lock the XMM-only float paths
;;   (VEXTRACTF32X4/VEXTRACTF64X2 + shuffles); no GPR may appear.

;; Comparison-produced condition: whole-lane blend is legal.
function %bitselect_i32x16_cmp(i32x16, i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16, v3: i32x16):
    v4 = icmp eq v0, v1
    v5 = bitselect v4, v2, v3
    return v5
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpcmpd $0x0, %zmm1, %zmm0, %k7
;   vpmovm2d %k7, %zmm0
;   vpmovd2m %zmm0, %k7
;   vpblendmd %zmm2, %zmm3, %zmm0 {%k7}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpcmpeqd %zmm1, %zmm0, %k7
;   vpmovm2d %k7, %zmm0
;   vpmovd2m %zmm0, %k7
;   vpblendmd %zmm2, %zmm3, %zmm0 {%k7}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; Arbitrary condition: must take the bitwise VPTERNLOG path.
function %bitselect_i32x16_raw(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = bitselect v0, v1, v2
    return v3
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogd $0xca, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogd $0xca, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %bitselect_i64x8_cmp(i64x8, i64x8, i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8, v2: i64x8, v3: i64x8):
    v4 = icmp eq v0, v1
    v5 = bitselect v4, v2, v3
    return v5
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpcmpq $0x0, %zmm1, %zmm0, %k7
;   vpmovm2q %k7, %zmm0
;   vpmovq2m %zmm0, %k7
;   vpblendmq %zmm2, %zmm3, %zmm0 {%k7}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpcmpeqq %zmm1, %zmm0, %k7
;   vpmovm2q %k7, %zmm0
;   vpmovq2m %zmm0, %k7
;   vpblendmq %zmm2, %zmm3, %zmm0 {%k7}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %bitselect_i64x8_raw(i64x8, i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8, v2: i64x8):
    v3 = bitselect v0, v1, v2
    return v3
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpternlogq $0xca, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpternlogq $0xca, %zmm2, %zmm1, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %swizzle_i32x16(i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16):
    v2 = swizzle v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movl $0x10, %esi
;   movd %esi, %xmm5
;   vpbroadcastd %xmm5, %zmm7
;   vpcmpud $0x1, %zmm7, %zmm1, %k2
;   vpermd %zmm0, %zmm1, %zmm0
;   uninit  %xmm1
;   vpxord %zmm1, %zmm1, %zmm1
;   vpblendmd %zmm0, %zmm1, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movl $0x10, %esi
;   movd %esi, %xmm5
;   vpbroadcastd %xmm5, %zmm7
;   vpcmpltud %zmm7, %zmm1, %k2
;   vpermd %zmm0, %zmm1, %zmm0
;   vpxord %zmm1, %zmm1, %zmm1
;   vpblendmd %zmm0, %zmm1, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %swizzle_i64x8(i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8):
    v2 = swizzle v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movl $0x8, %esi
;   movq %rsi, %xmm5
;   vpbroadcastq %xmm5, %zmm7
;   vpcmpuq $0x1, %zmm7, %zmm1, %k2
;   vpermq %zmm0, %zmm1, %zmm0
;   uninit  %xmm1
;   vpxorq %zmm1, %zmm1, %zmm1
;   vpblendmq %zmm0, %zmm1, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movl $8, %esi
;   movq %rsi, %xmm5
;   vpbroadcastq %xmm5, %zmm7
;   vpcmpltuq %zmm7, %zmm1, %k2
;   vpermq %zmm0, %zmm1, %zmm0
;   vpxorq %zmm1, %zmm1, %zmm1
;   vpblendmq %zmm0, %zmm1, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %extractlane_f32x16_0(f32x16) -> f32 {
block0(v0: f32x16):
    v1 = extractlane v0, 0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf32x4 $0x0, %zmm0, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf32x4 $0, %zmm0, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %extractlane_f32x16_5(f32x16) -> f32 {
block0(v0: f32x16):
    v1 = extractlane v0, 5
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf32x4 $0x1, %zmm0, %xmm2
;   pshufd $0x1, %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf32x4 $1, %zmm0, %xmm2
;   pshufd $1, %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %extractlane_f32x16_15(f32x16) -> f32 {
block0(v0: f32x16):
    v1 = extractlane v0, 15
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf32x4 $0x3, %zmm0, %xmm2
;   pshufd $0x3, %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf32x4 $3, %zmm0, %xmm2
;   pshufd $3, %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %extractlane_f64x8_0(f64x8) -> f64 {
block0(v0: f64x8):
    v1 = extractlane v0, 0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf64x2 $0x0, %zmm0, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf64x2 $0, %zmm0, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %extractlane_f64x8_7(f64x8) -> f64 {
block0(v0: f64x8):
    v1 = extractlane v0, 7
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf64x2 $0x3, %zmm0, %xmm2
;   pshufd $0xee, %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf64x2 $3, %zmm0, %xmm2
;   pshufd $0xee, %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %insertlane_f32x16_0(f32x16, f32) -> f32x16 {
block0(v0: f32x16, v1: f32):
    v2 = insertlane v0, v1, 0
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf32x4 $0x0, %zmm0, %xmm4
;   movss %xmm1, %xmm4
;   vinsertf32x4 $0x0, %xmm4, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf32x4 $0, %zmm0, %xmm4
;   movss %xmm1, %xmm4
;   vinsertf32x4 $0, %xmm4, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %insertlane_f32x16_6(f32x16, f32) -> f32x16 {
block0(v0: f32x16, v1: f32):
    v2 = insertlane v0, v1, 6
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf32x4 $0x1, %zmm0, %xmm5
;   shufps $0x30, %xmm5, %xmm1
;   shufps $0x84, %xmm1, %xmm5
;   vinsertf32x4 $0x1, %xmm5, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf32x4 $1, %zmm0, %xmm5
;   shufps $0x30, %xmm5, %xmm1
;   shufps $0x84, %xmm1, %xmm5
;   vinsertf32x4 $1, %xmm5, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %insertlane_f32x16_15(f32x16, f32) -> f32x16 {
block0(v0: f32x16, v1: f32):
    v2 = insertlane v0, v1, 15
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf32x4 $0x3, %zmm0, %xmm5
;   shufps $0xe4, %xmm5, %xmm1
;   shufps $0x24, %xmm1, %xmm5
;   vinsertf32x4 $0x3, %xmm5, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf32x4 $3, %zmm0, %xmm5
;   shufps $0xe4, %xmm5, %xmm1
;   shufps $0x24, %xmm1, %xmm5
;   vinsertf32x4 $3, %xmm5, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %insertlane_f64x8_0(f64x8, f64) -> f64x8 {
block0(v0: f64x8, v1: f64):
    v2 = insertlane v0, v1, 0
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf64x2 $0x0, %zmm0, %xmm4
;   movsd %xmm1, %xmm4
;   vinsertf64x2 $0x0, %xmm4, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf64x2 $0, %zmm0, %xmm4
;   movsd %xmm1, %xmm4
;   vinsertf64x2 $0, %xmm4, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %insertlane_f64x8_7(f64x8, f64) -> f64x8 {
block0(v0: f64x8, v1: f64):
    v2 = insertlane v0, v1, 7
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vextractf64x2 $0x3, %zmm0, %xmm4
;   movlhps %xmm1, %xmm4
;   vinsertf64x2 $0x3, %xmm4, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vextractf64x2 $3, %zmm0, %xmm4
;   movlhps %xmm1, %xmm4
;   vinsertf64x2 $3, %xmm4, %zmm0, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq


;; =============================================================================
;; Lane-mask strictness regressions (all_lanes_ones_or_zeros)
;; =============================================================================
;; The whole-lane VPBLENDMD/Q and masked-fusion lowerings sample only each
;; lane's sign bit (VPMOVD2M/Q), so they may fire only when the condition is
;; provably a LANE mask at the bitselect type's granularity. Byte-granular
;; masks (0x00/0xFF bytes, mixed within a lane) and lane-count-changing
;; bitcasts of comparisons must take the bitwise VPTERNLOG path.

;; vconst condition whose LANES are uniformly all-ones/all-zeros: the
;; whole-lane blend is still legal and must be used.
function %bitselect_i32x16_vconst_lanemask(i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16):
    v2 = vconst.i32x16 [0xffffffff 0 0xffffffff 0 0xffffffff 0 0xffffffff 0 0xffffffff 0 0xffffffff 0 0xffffffff 0 0xffffffff 0]
    v3 = bitselect v2, v0, v1
    return v3
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vmovdqu32 (%rip), %zmm5
;   vpmovd2m %zmm5, %k4
;   vpblendmd %zmm0, %zmm1, %zmm0 {%k4}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vmovdqu32 0x12(%rip), %zmm5
;   vpmovd2m %zmm5, %k4
;   vpblendmd %zmm0, %zmm1, %zmm0 {%k4}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   addb %bh, %bh

;; vconst condition whose BYTES are all 0x00/0xFF but whose 32-bit lanes are
;; NOT uniform (0x00ff00ff): must NOT take the sign-bit-sampling blend; must
;; lower to the bitwise VPTERNLOGD.
function %bitselect_i32x16_vconst_bytemask(i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16):
    v2 = vconst.i32x16 [0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff]
    v3 = bitselect v2, v0, v1
    return v3
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vmovdqu32 %zmm0, %zmm5
;   vmovdqu32 (%rip), %zmm0
;   vmovdqu32 %zmm5, %zmm6
;   vpternlogd $0xca, %zmm1, %zmm6, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vmovdqu32 %zmm0, %zmm5
;   vmovdqu32 0x1c(%rip), %zmm0
;   vmovdqu32 %zmm5, %zmm6
;   vpternlogd $0xca, %zmm1, %zmm6, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)

;; 64-bit lanes of 0x00000000ffffffff: uniform at 32-bit granularity but not
;; at the bitselect type's 64-bit granularity -> bitwise VPTERNLOGQ.
function %bitselect_i64x8_vconst_bytemask(i64x8, i64x8) -> i64x8 {
block0(v0: i64x8, v1: i64x8):
    v2 = vconst.i64x8 [0x00000000ffffffff 0x00000000ffffffff 0x00000000ffffffff 0x00000000ffffffff 0x00000000ffffffff 0x00000000ffffffff 0x00000000ffffffff 0x00000000ffffffff]
    v3 = bitselect v2, v0, v1
    return v3
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vmovdqu32 %zmm0, %zmm5
;   vmovdqu64 (%rip), %zmm0
;   vmovdqu32 %zmm5, %zmm6
;   vpternlogq $0xca, %zmm1, %zmm6, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vmovdqu32 %zmm0, %zmm5
;   vmovdqu64 0x1c(%rip), %zmm0
;   vmovdqu32 %zmm5, %zmm6
;   vpternlogq $0xca, %zmm1, %zmm6, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)

;; bitcast.i64x8 of an fcmp on f32x16: the comparison's lanes are 32-bit,
;; the bitselect's are 64-bit, so this is a byte mask but not a 64-bit lane
;; mask -> bitwise VPTERNLOGQ, never VPBLENDMQ.
function %bitselect_i64x8_bitcast_fcmp(f32x16, f32x16, i64x8, i64x8) -> i64x8 {
block0(v0: f32x16, v1: f32x16, v2: i64x8, v3: i64x8):
    v4 = fcmp eq v0, v1
    v5 = bitcast.i64x8 little v4
    v6 = bitselect v5, v2, v3
    return v6
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vcmpps $0x0, %zmm1, %zmm0, %k6
;   vpmovm2d %k6, %zmm0
;   vpternlogq $0xca, %zmm3, %zmm2, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vcmpeqps %zmm1, %zmm0, %k6
;   vpmovm2d %k6, %zmm0
;   vpternlogq $0xca, %zmm3, %zmm2, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; Positive fusion lock: an icmp-produced mask still fuses
;; bitselect(mask, iadd(x, y), passthru) into a single merge-masked VPADDD.
function %fusion_iadd_i32x16_icmp_mask(i32x16, i32x16, i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16, v3: i32x16, v4: i32x16):
    v5 = icmp eq v0, v1
    v6 = iadd v2, v3
    v7 = bitselect v5, v6, v4
    return v7
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vpcmpd $0x0, %zmm1, %zmm0, %k2
;   vpmovm2d %k2, %zmm0
;   vpmovd2m %zmm0, %k2
;   vmovdqu32 %zmm4, %zmm0
;   vpaddd %zmm3, %zmm2, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpcmpeqd %zmm1, %zmm0, %k2
;   vpmovm2d %k2, %zmm0
;   vpmovd2m %zmm0, %k2
;   vmovdqu32 %zmm4, %zmm0
;   vpaddd %zmm3, %zmm2, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

;; Negative fusion lock: a byte-granular vconst mask must NOT fuse; expect a
;; plain VPADDD followed by the bitwise VPTERNLOGD select.
function %fusion_iadd_i32x16_bytemask(i32x16, i32x16, i32x16) -> i32x16 {
block0(v0: i32x16, v1: i32x16, v2: i32x16):
    v3 = vconst.i32x16 [0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff 0x00ff00ff]
    v4 = iadd v0, v1
    v5 = bitselect v3, v4, v2
    return v5
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vmovdqu32 %zmm0, %zmm3
;   vmovdqu32 (%rip), %zmm0
;   vpaddd %zmm1, %zmm3, %zmm6
;   vpternlogd $0xca, %zmm2, %zmm6, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vmovdqu32 %zmm0, %zmm3
;   vmovdqu32 0x1c(%rip), %zmm0
;   vpaddd %zmm1, %zmm3, %zmm6
;   vpternlogd $0xca, %zmm2, %zmm6, %zmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)
;   incl (%rax)

;; Positive lock for the same-lane-count bitcast arm: the canonical float
;; mask pattern bitcast.f32x16(fcmp on f32x16) keeps the masked VADDPS
;; fusion (32-bit lanes on both sides of the bitcast).
function %fusion_fadd_f32x16_bitcast_fcmp(f32x16, f32x16, f32x16, f32x16, f32x16) -> f32x16 {
block0(v0: f32x16, v1: f32x16, v2: f32x16, v3: f32x16, v4: f32x16):
    v5 = fcmp gt v0, v1
    v6 = bitcast.f32x16 little v5
    v7 = fadd v2, v3
    v8 = bitselect v6, v7, v4
    return v8
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   vcmpps $0x1, %zmm0, %zmm1, %k2
;   vpmovm2d %k2, %zmm0
;   vpmovd2m %zmm0, %k2
;   vmovdqu32 %zmm4, %zmm0
;   vaddps %zmm3, %zmm2, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vcmpltps %zmm0, %zmm1, %k2
;   vpmovm2d %k2, %zmm0
;   vpmovd2m %zmm0, %k2
;   vmovdqu32 %zmm4, %zmm0
;   vaddps %zmm3, %zmm2, %zmm0 {%k2}
;   movq %rbp, %rsp
;   popq %rbp
;   retq

